# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'can.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CanForm(object):
    def setupUi(self, CanForm):
        CanForm.setObjectName("CanForm")
        CanForm.resize(824, 565)
        self.textEdit_Recv = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Recv.setGeometry(QtCore.QRect(30, 20, 491, 521))
        self.textEdit_Recv.setObjectName("textEdit_Recv")
        self.textEdit_Info = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Info.setGeometry(QtCore.QRect(540, 200, 261, 341))
        self.textEdit_Info.setObjectName("textEdit_Info")
        self.splitter_2 = QtWidgets.QSplitter(CanForm)
        self.splitter_2.setGeometry(QtCore.QRect(540, 110, 261, 31))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.comboBox_Ycyk = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_Ycyk.setObjectName("comboBox_Ycyk")
        self.pushButton_Send = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.splitter = QtWidgets.QSplitter(CanForm)
        self.splitter.setGeometry(QtCore.QRect(540, 40, 261, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.comboBox_Type = QtWidgets.QComboBox(self.splitter)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.pushButton_Open = QtWidgets.QPushButton(self.splitter)
        self.pushButton_Open.setObjectName("pushButton_Open")

        self.retranslateUi(CanForm)
        QtCore.QMetaObject.connectSlotsByName(CanForm)

    def retranslateUi(self, CanForm):
        _translate = QtCore.QCoreApplication.translate
        CanForm.setWindowTitle(_translate("CanForm", "Form"))
        self.pushButton_Send.setText(_translate("CanForm", "发送"))
        self.pushButton_Open.setText(_translate("CanForm", "打开设备"))
