# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_bmu_debug.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_Output = TextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(140)
        sizePolicy.setHeightForWidth(self.textEdit_Output.sizePolicy().hasHeightForWidth())
        self.textEdit_Output.setSizePolicy(sizePolicy)
        self.textEdit_Output.setObjectName("textEdit_Output")
        self.verticalLayout.addWidget(self.textEdit_Output)
        self.lineEdit_Input = LineEdit(Form)
        self.lineEdit_Input.setObjectName("lineEdit_Input")
        self.verticalLayout.addWidget(self.lineEdit_Input)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "控制台"))
from qfluentwidgets import LineEdit, TextEdit
