# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'can.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_CanForm(object):
    def setupUi(self, CanForm):
        CanForm.setObjectName("CanForm")
        CanForm.resize(905, 770)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CanForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_Recv = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Recv.setObjectName("textEdit_Recv")
        self.horizontalLayout_2.addWidget(self.textEdit_Recv)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Open = QtWidgets.QPushButton(CanForm)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.verticalLayout.addWidget(self.pushButton_Open)
        self.comboBox_Type = QtWidgets.QComboBox(CanForm)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.verticalLayout.addWidget(self.comboBox_Type)
        self.pushButton_TableView = QtWidgets.QPushButton(CanForm)
        self.pushButton_TableView.setObjectName("pushButton_TableView")
        self.verticalLayout.addWidget(self.pushButton_TableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.textEdit_Info = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Info.setObjectName("textEdit_Info")
        self.verticalLayout_2.addWidget(self.textEdit_Info)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_sendFlag = QtWidgets.QCheckBox(CanForm)
        self.checkBox_sendFlag.setText("")
        self.checkBox_sendFlag.setObjectName("checkBox_sendFlag")
        self.gridLayout.addWidget(self.checkBox_sendFlag, 2, 1, 1, 1)
        self.comboBox_sendTime_lag = EditableComboBox(CanForm)
        self.comboBox_sendTime_lag.setProperty("editable", True)
        self.comboBox_sendTime_lag.setObjectName("comboBox_sendTime_lag")
        self.gridLayout.addWidget(self.comboBox_sendTime_lag, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(CanForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.pushButton_Send = QtWidgets.QPushButton(CanForm)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.gridLayout.addWidget(self.pushButton_Send, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(CanForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.comboBox_sendTimes = EditableComboBox(CanForm)
        self.comboBox_sendTimes.setProperty("editable", True)
        self.comboBox_sendTimes.setObjectName("comboBox_sendTimes")
        self.gridLayout.addWidget(self.comboBox_sendTimes, 1, 1, 1, 3)
        self.comboBox_Ycyk = QtWidgets.QComboBox(CanForm)
        self.comboBox_Ycyk.setObjectName("comboBox_Ycyk")
        self.gridLayout.addWidget(self.comboBox_Ycyk, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(CanForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(CanForm)
        QtCore.QMetaObject.connectSlotsByName(CanForm)

    def retranslateUi(self, CanForm):
        _translate = QtCore.QCoreApplication.translate
        CanForm.setWindowTitle(_translate("CanForm", "Form"))
        self.pushButton_Open.setText(_translate("CanForm", "打开设备"))
        self.pushButton_TableView.setText(_translate("CanForm", "芜湖"))
        self.label_3.setText(_translate("CanForm", "发送间隔ms"))
        self.pushButton_Send.setText(_translate("CanForm", "发送"))
        self.label.setText(_translate("CanForm", "连续发送开关"))
        self.label_2.setText(_translate("CanForm", "发送次数"))
from qfluentwidgets import EditableComboBox
