# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'can.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CanForm(object):
    def setupUi(self, CanForm):
        CanForm.setObjectName("CanForm")
        CanForm.resize(824, 776)
        self.textEdit_Recv = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Recv.setGeometry(QtCore.QRect(30, 20, 491, 521))
        self.textEdit_Recv.setObjectName("textEdit_Recv")
        self.textEdit_Info = QtWidgets.QTextEdit(CanForm)
        self.textEdit_Info.setGeometry(QtCore.QRect(540, 200, 261, 341))
        self.textEdit_Info.setObjectName("textEdit_Info")
        self.splitter_2 = QtWidgets.QSplitter(CanForm)
        self.splitter_2.setGeometry(QtCore.QRect(540, 730, 261, 31))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.comboBox_Ycyk = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_Ycyk.setObjectName("comboBox_Ycyk")
        self.pushButton_Send = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.widget = QtWidgets.QWidget(CanForm)
        self.widget.setGeometry(QtCore.QRect(540, 40, 251, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Open = QtWidgets.QPushButton(self.widget)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.verticalLayout.addWidget(self.pushButton_Open)
        self.comboBox_Type = QtWidgets.QComboBox(self.widget)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.verticalLayout.addWidget(self.comboBox_Type)
        self.pushButton_Close = QtWidgets.QPushButton(self.widget)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.verticalLayout.addWidget(self.pushButton_Close)

        self.retranslateUi(CanForm)
        QtCore.QMetaObject.connectSlotsByName(CanForm)

    def retranslateUi(self, CanForm):
        _translate = QtCore.QCoreApplication.translate
        CanForm.setWindowTitle(_translate("CanForm", "Form"))
        self.pushButton_Send.setText(_translate("CanForm", "发送"))
        self.pushButton_Open.setText(_translate("CanForm", "打开设备"))
        self.pushButton_Close.setText(_translate("CanForm", "关闭设备"))
